name: ğŸ” Review

on:
  workflow_run:
    workflows: ["ğŸ§‘â€ğŸ’» Development"]
    types:
      - completed
    

permissions:
  contents: read
  pull-requests: write

jobs:
  add-reviews:
    name: ğŸ‘¥ Auto-assign Reviewer and Assignee
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘¤ assigning reviewr and assignee
        uses: kentaro-m/auto-assign-action@v2.0.0
  danger:
    name: âš¡ Danger Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: â˜ï¸ checkout repository
        uses: actions/checkout@v4

      - name: ğŸ”§ setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: ğŸ”§ setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: ğŸ“¦ install dependencies
        run: pnpm install

      - name: âš¡ run danger file
        run: pnpm check:danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
