name: ğŸ“¸ Update Snapshots on Comment

#on:
#  issue_comment:
#    types:
#      - created
#      - edited
#      - deleted
#  workflow_call:

on: issue_comment


jobs:
  # _________________________________
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
  # _________________________________
  update-snapshots:
    name: Update Snapshots
#    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/approve-snapshots') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: test
        run: echo hi
#      - name: ğŸ” get PR branch
#        uses: xt0rted/pull-request-comment-branch@v2
#        id: comment-branch
#
#      - name: â˜ï¸ checkout PR branch
#        uses: actions/checkout@v4
#        with:
#          ref: ${{ steps.comment-branch.outputs.head_ref }}
#
#      - name: âœï¸ comment action started
#        uses: thollander/actions-comment-pull-request@v3
#        with:
#          message: |
#            â³ Updating snapshots. Click [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) to see the status.
#
#      - name: "ğŸ”§ setup node"
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: "pnpm"
#
#      - name: ğŸ“¦ install dependencies
#        run: pnpm install
#
#      - name: ğŸ­ install playwright
#        run: pnpm playwright install --with-deps --only-shell
#
#        # Set up GitHub Actions caching for Wireit.
#      - name: ğŸ”Œ setup wireit cache
#        uses: google/wireit@setup-github-actions-caching/v2
#
#      - name: ğŸ“¸ update snapshots
#        run: pnpm exec playwright test --update-snapshots
#
#      - name: âš™ï¸ commit and push updated snapshots
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: 'Update e2e snapshots'
#
#      - name: âœ… comment success
#        uses: thollander/actions-comment-pull-request@v3
#        with:
#          message: |
#            âœ… Successfully updated and committed Playwright snapshots!
